#!/bin/bash

# GhostOffice Installation Script
# For Linux and macOS
# Version 3.1.0

set -e

echo "👻 GhostOffice Installation Script"
echo "=================================="
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then 
    echo "⚠️  Please do not run this script as root"
    exit 1
fi

# Detect OS
OS="$(uname -s)"
case "${OS}" in
    Linux*)     MACHINE=Linux;;
    Darwin*)    MACHINE=Mac;;
    *)          MACHINE="UNKNOWN:${OS}"
esac

echo "🖥️  Detected OS: ${MACHINE}"
echo ""

# Check Python version
echo "🐍 Checking Python installation..."
if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 is not installed. Please install Python 3.8 or higher first."
    echo ""
    echo "Ubuntu/Debian: sudo apt-get install python3 python3-pip python3-venv"
    echo "macOS: brew install python3"
    exit 1
fi

PYTHON_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1,2)
echo "✅ Found Python ${PYTHON_VERSION}"

# Check if Python version is >= 3.8
if [ "$(printf '%s\n' "3.8" "${PYTHON_VERSION}" | sort -V | head -n1)" != "3.8" ]; then
    echo "❌ Python 3.8 or higher is required. Found ${PYTHON_VERSION}"
    exit 1
fi

echo ""

# Check if Ollama is installed
echo "🧠 Checking Ollama installation..."
if ! command -v ollama &> /dev/null; then
    echo "⚠️  Ollama is not installed. Installing Ollama..."
    
    if [ "${MACHINE}" = "Linux" ]; then
        curl -fsSL https://ollama.com/install.sh | sh
    elif [ "${MACHINE}" = "Mac" ]; then
        echo "Please install Ollama from https://ollama.com/download"
        echo "Or run: brew install ollama"
        exit 1
    fi
else
    echo "✅ Ollama is installed"
fi

echo ""

# Create virtual environment
echo "📦 Creating virtual environment..."
if [ -d "venv" ]; then
    echo "⚠️  Virtual environment already exists. Removing old one..."
    rm -rf venv
fi

python3 -m venv venv
echo "✅ Virtual environment created"

echo ""

# Activate virtual environment and install dependencies
echo "📚 Installing Python dependencies..."
source venv/bin/activate

# Upgrade pip
pip install --upgrade pip

# Install requirements
if [ -f "requirements.txt" ]; then
    pip install -r requirements.txt
    echo "✅ Dependencies installed"
else
    echo "❌ requirements.txt not found"
    exit 1
fi

echo ""

# Pull default Ollama model
echo "🤖 Pulling default Ollama model (phi3:mini)..."
ollama pull phi3:mini
echo "✅ Model pulled"

echo ""

# Create .env file if it doesn't exist
if [ ! -f ".env" ]; then
    echo "📝 Creating .env file..."
    cat > .env << EOF
# GhostOffice Configuration
# Generated by install.sh

# Ollama Configuration
OLLAMA_HOST=http://localhost:11434
OLLAMA_MODEL=phi3:mini
OLLAMA_BACKUP_MODEL=llama3.2:3b

# Dashboard Configuration
DASHBOARD_PORT=5000
DASHBOARD_HOST=127.0.0.1

# Demo Mode (set to true for demo mode)
DEMO_MODE=false

# Setup Status
SETUP_COMPLETE=false

# Watch Folders (comma-separated)
WATCH_FOLDERS=~/Downloads,~/Desktop
ORGANIZED_ROOT=~/Documents/Organized

# Performance Settings
CYCLE_INTERVAL_MINUTES=5
MAX_EMAILS_PER_CYCLE=50
MAX_FILES_PER_CYCLE=30

# Security Settings
AUTO_LOCK_MINUTES=30
SESSION_TIMEOUT_HOURS=8
MAX_LOGIN_ATTEMPTS=5
LOCKOUT_MINUTES=15

# Email Automation
AUTO_SEND_DRAFTS=false
AUTO_SEND_TRUSTED_ONLY=true
DRAFT_CONFIRMATION_REQUIRED=true

# Notifications
ENABLE_DESKTOP_NOTIFICATIONS=true
ENABLE_SOUND=true

# Compliance
ENABLE_GDPR=true
ENABLE_HIPAA=true
EOF
    echo "✅ .env file created"
else
    echo "⚠️  .env file already exists"
fi

echo ""

# Create data directories
echo "📁 Creating data directories..."
mkdir -p data/{logs,audit,backups,temp,reports,processed,pending,attachments,calendar_pending}
mkdir -p calendar
echo "✅ Data directories created"

echo ""

# Installation complete
echo "=================================="
echo "✅ Installation Complete!"
echo ""
echo "🚀 To start GhostOffice:"
echo ""
echo "   cd $(pwd)"
echo "   source venv/bin/activate"
echo "   python3 main.py"
echo ""
echo "🌐 The web dashboard will be available at: http://localhost:5000"
echo ""
echo "📖 For more information, see README.md"
echo ""
echo "👻 Thank you for choosing GhostOffice!"
echo ""
